#!/bin/bash
clear
echo -e "\033[1;33mUserback options:\033[1;30m
1) Eliminar usuario
2) Eliminar o desconectar todos los usuarios
3) Desconectar todos los usuarios\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Que o nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario não existe"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuario $name fue Removido"
 exit
 fi

 if [ $option -eq 2 ]; then
 read -p "Que nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "Usuario $name fue parado y removido"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Que de nombre de usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "Usuario $name fue parado"
 exit
 fi
